### ISSUE TITLE
Integrating reva based authentication

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-online#1]
Describo has two methods for authenticating users:
* okta: https://github.com/Arkisto-Platform/describo-online/blob/master/documentation/okta-authentication.md
* external service: https://github.com/Arkisto-Platform/describo-online/blob/master/documentation/sid-authentication.md

Describo is driven by a configuration file as documented at https://github.com/Arkisto-Platform/describo-online/blob/master/documentation/configuration.md:

# Reva integration
Reva authentication will be similar to the okta flow. Following is a possible way to do it.

## Configuration change
  * update UI configuration with a top level property `authentication` that defines the auth method for this installation  'okta' || 'reva'

## In the UI code
  * create UI component `@components/Login.component.vue` and wire up to the `/login` route in routes.js
    *  The login component should use the configuration stored in the store to either load the `OktaLoginComponent` or the `RevaLoginComponent`
    * Implement `@/components/RevaLogin.component.vue` which knows how to perform reva logins (in the Ailleron implementation you post to the API which then talks to Reva. Can this component talk to Reva directly the way the okta component does?`
    * The `RevaLoginComponent` should then store the token in local | session storage and POST back to the API to create a session for the user (pretty much the same as what happens in `@components/OktaLoginCallback.component`.
    * update `http.service.getHeaders` to get the `reva` token or `okta` based on the `authentication` property in the configuration
    * refactor: might be worth extracting `OktaLoginComponent` and `RevaLoginComponent` as vue plugins in https://github.com/Arkisto-Platform/describo-ui-plugins

## In the API code

* implement and wire up `/session/reva` in `@/routes/index.js`. It can be almost exactly like the handler for `/session/okta` but calling reva to check the passed in token. Instantiate a DB session for the user to use the rest of the time in the same way as happens for the okta session.
    * probably worth refactoring this file and extracting the session handlers
* update `@/middleware/demandKnownUser` with an option to handle `authorization: reva ...` in the headers. Again, this will work the same way as okta where the session lookup happens on the db.
* if doing the auth to Reva from the API: add a route that the UI form can post to which then auth's against Reva.

**Comment by piotrWichlinskiSoftwaremind** [comment]
Task development plan:
- Add Reva box into describo-online
- Add CS3 API to handle Reva connections on the backend (this should be an npm package but for now I will add my generated API and check if the npm package is working)
- Modify authorization endpoints to fit Reva schema, this includes moving my libraries written to handle Reva API 
- Create UI plugin with authentication form and use Reva token generated in API

**Comment by marcolarosa** [comment]
done
