### ISSUE TITLE
Refresh should not make the user lose their place

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/describo-online#16]
If you hit refresh (eg cos there's an annoying alert) then it goes back to the root of your data. I would expect it to refresh the screen where I am currently working).

**Comment by ptsefton** [comment]
I know there's a reason but I can't remember - why can't the URL show a path to the dataset you're working on relative to the root you connected to?

**Comment by marcolarosa** [comment]
> If you hit refresh (eg cos there's an annoying alert) then it goes back to the root of your data. I would expect it to refresh the screen where I am currently working).

So about this - can you please keep track of these annoying alerts and report where / when so I can see if they're configured properly. They shouldn't be annoying and we need to know why they're happening.

**Comment by marcolarosa** [comment]
done by https://github.com/Arkisto-Platform/describo-online/commit/b900eae5f574f2512a7016312112cb0a3b5fcacd
