### ISSUE TITLE
File preview components not loading

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-online#31]
check browser console

**Comment by marcolarosa** [comment]
@ptsefton I'm thinking of removing the file preview stuff from describo for now. Of all the backends supported only onedrive (business, not personal) and s3 support getting a direct file link that can be used to display a preview.

Owncloud, reva and local don't have that capability so I would need to somehow stream the file content to the browser for display in each of those cases. What do you think?

**Comment by ptsefton** [comment]
Ok for now - but it will be key to some scenarios, I guess those folks will need to use a desktop version, once that work is re-started.

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by marcolarosa** [comment]
Disabled for now 455000415082ef3b5a6becafd78437efa7adb387
