### ISSUE TITLE
Allow ARCPs as IDs and do not add a #

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/describo-online#39]
If you change an item's ID to something that uses the arcp:// URI scheme it gets prepended with a # -- maybe this should be coded to comply with the JSON-LD spec so there are no surprises later.

> If the [node object](https://json-ld.org/spec/latest/json-ld/#dfn-node-objects) contains the @id key, its value MUST be an [absolute IRI](https://json-ld.org/spec/latest/json-ld/#dfn-absolute-iris), a [relative IRI](https://json-ld.org/spec/latest/json-ld/#dfn-relative-iris), or a [compact IRI](https://json-ld.org/spec/latest/json-ld/#dfn-compact-iris) (including [blank node identifiers](https://json-ld.org/spec/latest/json-ld/#dfn-blank-node-identifiers)). See [§ 3.3 Node Identifiers](https://json-ld.org/spec/latest/json-ld/#node-identifiers), [§ 4.4 Compact IRIs](https://json-ld.org/spec/latest/json-ld/#compact-iris), and [§ 4.16 Identifying Blank Nodes](https://json-ld.org/spec/latest/json-ld/#identifying-blank-nodes) for further discussion on @id values.
> Source: <https://json-ld.org/spec/latest/json-ld/#node-objects>

**Comment by marcolarosa** [comment]
Ahh, I hadn't considered that!

The code currently is quite simple (https://github.com/Arkisto-Platform/describo-online/blob/master/api/src/lib/crate.js#L528-L530): 

* if (`isURL(id)`) then use as is (isURL comes from https://github.com/validatorjs/validator.js and by default it validates to true for http, https and ftp).
* else if `id === ./` use as is
* else if `id starts with #` use as is
* else prepend # and return.

I can pass a protocols list to isURL (http, https, ftp, file, arcp) which means we can control what is a url or not but also means we need a new release if we need to add a protocol. Or, it can be a regex like `^[a-z,A-Z]+\:\/\/.*`  (basically [anything]://[anything])`.

It also (currently) doesn't support id's starting with '/'. So i'm thinking we add protocols list to isURL and I also check that id's starting with './' or '/' are used as is.

**Comment by marcolarosa** [comment]
So reading that json-ld page suggests it should be something like:

* return if uri as matched by regex looking for ([scheme = anything]://.*) [see huge list of schemes](https://en.wikipedia.org/wiki/List_of_URI_schemes)
* return if matches regex ([prefix = anything]:.*) as it looks like a reference to the context
* return if matches ^_:, or /^.?\//gm (starts with ./ or /)
* return if matches ^#
* otherwise return with prefix of #

**Comment by ptsefton** [comment]
The second case covers the first
