### ISSUE TITLE
Form should NOT reorder itself

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/describo-online#42]
Currently if you add something to a property then that jumps to the top of the form. This is counter to the way forms normally work on the web and is confusing. (I know this was requested by someone, but IMO it is not a good UI choice - one we have the ability to split a profile into tabs or groups then the number of form fields showing at any one time will get smaller. Properties that are not essential can be shunted to an "Advanced"  tab where they are out of sight for most users.

**Comment by marcolarosa** [comment]
Resolved by https://github.com/Arkisto-Platform/describo-online/commit/d06f35bdea2400bbc214c74910081a0c83965159 and improved by https://github.com/Arkisto-Platform/describo-online/commit/903b8a6af48607288a38dd0ead42f93f8dc36367
