### ISSUE TITLE
Show the name above the map for Geo locations 

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/describo-online#52]
This has a name but it is not showing alongside  the prop (also the map or the yellow box do not seem to be click-to-edit-able - I was not able to get back to the data entry screen to edit it.

![image](https://user-images.githubusercontent.com/756184/180328682-95cb5fe8-d1ee-4ec8-bde4-4ecea16c2069.png)

**Comment by marcolarosa** [comment]
@ptsefton I'll add the name property as requested. The click to edit is a little more nuanced. As this entity could be used elsewhere in the crate do we want to allow the edit capability or require the user to unlink and create a new location? I figured the latter approach would result in less confusion. Thoughts?

**Comment by ptsefton** [comment]
I think that if it's used elsewhere then it's still the same entity and should be editable in the same way as any other entity.

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________
