### ISSUE TITLE
[Documentation] Wiki unclear about session creation in embedded mode

### ISSUE THREAD

**Issue by juriroemer** [Arkisto-Platform/describo-online#56]
Regarding [Integrating Describo Online into owncloud](https://github.com/Arkisto-Platform/describo-online/wiki/Integrating-Describo-Online-into-owncloud): In the initial definition of the `POST` session creation object, the key in L:4 is given as `service`, whilst the example below shows the key as `session`.

Looking at [23e2fca](https://github.com/Arkisto-Platform/describo-online/commit/23e2fcad3f4bc72f705796e883a2dc3846cb3841), I'm assuming that `service` is the currently correct key name.

**Comment by marcolarosa** [comment]
Good spot - i've updated the example. Thanks!

**Comment by juriroemer** [comment]
Just realized I linked the parent - meant to link c685706e of course!

Thanks! :)
