### ISSUE TITLE
Properties with sub properties

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-online#9]
Can we define in the profile some configuration that tells the UI to render a contributor field but when going to add one you get a dropdown of the sub contributor properties  (e.g. annotator, depositor etc). 

Potential UX issues: a user adds a contributor as annotator but then when the crate loads up next time we see the annotator field with the value. Is this an issue? To be determined.

**Comment by marcolarosa** [comment]
@ptsefton add screenshots of profile showing extra metadata

Add properties "group" and "bundlePropertyAs" to each input. 
* Group is a grouping structure that the UI will use to create a more forms based interface (e.g. tabs). Think who, what, where etc.
* BundlePropertyAs: property name comes from this field and it shows a complex selector which allows the user to select the attribute (e.g. annotator, recorder etc) and then create the data (link a person etc)

**Comment by ptsefton** [comment]
![image](https://user-images.githubusercontent.com/756184/158107462-51b14d16-4c32-41ae-8c35-f0149dbf8c16.png)

![image](https://user-images.githubusercontent.com/756184/158107503-a245658e-fc20-4ebf-9c20-2b0a775f424b.png)

**Comment by marcolarosa** [comment]
Grouping work has been moved to https://github.com/Arkisto-Platform/describo-online/issues/46
